version: 2.1
commands:

  abort_for_docs:
    steps:
      - run:
          name: Avoid tests for docs
          command: |
            if [[ $CIRCLE_BRANCH == *docs ]]; then
              echo "Identifies as documents PR, no testing required"
              circleci step halt
            fi

  abort_for_noci:
    steps:
      - run:
          name: Ignore CI for specific branches
          command: |
            if [[ $CIRCLE_BRANCH == *noci ]]; then
              echo "Identifies as actively ignoring CI, no testing required."
              circleci step halt
            fi

  early_return_for_forked_pull_requests:
    description: >-
      If this build is from a fork, stop executing the current job and return success.
      This is useful to avoid steps that will fail due to missing credentials.
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci step halt
            fi

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0-browsers
      - image: redislabs/redis:6.0.12-58

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - abort_for_docs
      - abort_for_noci
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - spark-redis-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: spark-redis-{{ checksum "pom.xml" }}

      - run:
          name: Run Test
          command: |
            make test

      - early_return_for_forked_pull_requests
      - run: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
      - run: bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov) -t ${CODECOV_TOKEN}
      - run: mvn -s .circleci.settings.xml -DskipTests -Dgpg.skip deploy

workflows:
  version: 2
  commit:
    jobs:
      - build
